"""Add user_trades table

Revision ID: 063ec00d739b
Revises: 859646cd3920
Create Date: 2026-02-20 13:21:04.840498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063ec00d739b'
down_revision = '859646cd3920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nifty_price', sa.Float(), nullable=True),
    sa.Column('trade_symbol', sa.String(length=100), nullable=False),
    sa.Column('trade_instrument_token', sa.BigInteger(), nullable=True),
    sa.Column('option_type', sa.String(length=5), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('actual_entry_price', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('actual_exit_price', sa.Float(), nullable=True),
    sa.Column('trade_status', sa.String(length=20), nullable=False),
    sa.Column('trade_mode', sa.String(length=20), nullable=False),
    sa.Column('kite_order_id_entry', sa.String(length=50), nullable=True),
    sa.Column('kite_order_id_exit', sa.String(length=50), nullable=True),
    sa.Column('oi_trend', sa.String(length=50), nullable=True),
    sa.Column('avg_oi_change_5min', sa.Float(), nullable=True),
    sa.Column('capital_used', sa.Float(), nullable=True),
    sa.Column('closing_pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percentage', sa.Float(), nullable=True),
    sa.Column('max_pnl', sa.Float(), nullable=True),
    sa.Column('min_pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_trades_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_trades_trade_status'), ['trade_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_trades_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_trades_trade_status'))
        batch_op.drop_index(batch_op.f('ix_user_trades_trade_date'))

    op.drop_table('user_trades')
    # ### end Alembic commands ###
