"""Add Instrument model for Kite instruments data

Revision ID: 1e58e806b584
Revises: 820b928eadc5
Create Date: 2026-02-15 01:10:19.025928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e58e806b584'
down_revision = '820b928eadc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_token', sa.BigInteger(), nullable=False),
    sa.Column('exchange_token', sa.BigInteger(), nullable=True),
    sa.Column('tradingsymbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('fetch_date', sa.Date(), nullable=False),
    sa.Column('expiry_weekday', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_fetch_date'), ['fetch_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_instrument_token'), ['instrument_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_tradingsymbol'), ['tradingsymbol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_tradingsymbol'))
        batch_op.drop_index(batch_op.f('ix_instruments_instrument_token'))
        batch_op.drop_index(batch_op.f('ix_instruments_fetch_date'))
        batch_op.drop_index(batch_op.f('ix_instruments_exchange'))

    op.drop_table('instruments')
    # ### end Alembic commands ###
