"""Add option_chain_data table

Revision ID: 4b9cff2d64bb
Revises: ace9da728d74
Create Date: 2026-02-15 01:56:03.951238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9cff2d64bb'
down_revision = 'ace9da728d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_chain_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('ce_oi', sa.Integer(), nullable=True),
    sa.Column('ce_oi_change', sa.Integer(), nullable=True),
    sa.Column('ce_volume', sa.Integer(), nullable=True),
    sa.Column('ce_ltp', sa.Float(), nullable=True),
    sa.Column('ce_change', sa.Float(), nullable=True),
    sa.Column('ce_change_percent', sa.Float(), nullable=True),
    sa.Column('ce_iv', sa.Float(), nullable=True),
    sa.Column('pe_oi', sa.Integer(), nullable=True),
    sa.Column('pe_oi_change', sa.Integer(), nullable=True),
    sa.Column('pe_volume', sa.Integer(), nullable=True),
    sa.Column('pe_ltp', sa.Float(), nullable=True),
    sa.Column('pe_change', sa.Float(), nullable=True),
    sa.Column('pe_change_percent', sa.Float(), nullable=True),
    sa.Column('pe_iv', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_current_expiry', sa.Boolean(), nullable=True),
    sa.Column('ce_strike_symbol', sa.String(length=100), nullable=True),
    sa.Column('ce_instrument_token', sa.String(length=50), nullable=True),
    sa.Column('pe_strike_symbol', sa.String(length=100), nullable=True),
    sa.Column('pe_instrument_token', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option_chain_data')
    # ### end Alembic commands ###
