"""Initial migration with User model

Revision ID: 820b928eadc5
Revises: 
Create Date: 2026-02-15 00:36:05.357438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820b928eadc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.Column('api_secret', sa.String(length=100), nullable=True),
    sa.Column('request_token', sa.Text(), nullable=True),
    sa.Column('kite_callback_token', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('trade_mode', sa.String(length=20), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('account_growth_percentage', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kite_account_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_balance_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_kite_callback_token'), ['kite_callback_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_kite_callback_token'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
