"""Add index_data table

Revision ID: 859646cd3920
Revises: 4b9cff2d64bb
Create Date: 2026-02-15 02:53:41.074366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859646cd3920'
down_revision = '4b9cff2d64bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('instrument_token', sa.Integer(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('ma_20', sa.Float(), nullable=True),
    sa.Column('ma_200', sa.Float(), nullable=True),
    sa.Column('fast_ma_39', sa.Float(), nullable=True),
    sa.Column('fast_ma_69', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('supertrend', sa.Float(), nullable=True),
    sa.Column('supertrend_direction', sa.Integer(), nullable=True),
    sa.Column('super_power', sa.String(length=20), nullable=True),
    sa.Column('super_power_brick', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('index_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_index_data_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_index_data_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_data_timestamp'))
        batch_op.drop_index(batch_op.f('ix_index_data_symbol'))

    op.drop_table('index_data')
    # ### end Alembic commands ###
